spring:
  application:
    name: taco-cloud-api
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_in_actions
    username: postgres
    password: dv9899
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  data:
    rest:
      base-path: /data-api
server:
  port: 8080
